services:
  - type: web
    name: raftlabs-backend
    runtime: node
    plan: free  # <--- THIS keeps it free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
